DROP TABLE IF EXISTS PERSONNEL_ACCUEIL;
DROP TABLE IF EXISTS PERSONNEL;
DROP TABLE IF EXISTS DEPLACE;
DROP TABLE IF EXISTS TRANSPORT;
DROP TABLE IF EXISTS RESTAURATION;
DROP TABLE IF EXISTS RESTAURANT;
DROP TABLE IF EXISTS COMMENTAIRE;
DROP TABLE IF EXISTS CONCERT;
DROP TABLE IF EXISTS PARKING;
DROP TABLE IF EXISTS MATERIEL;
DROP TABLE IF EXISTS HEBERGEMENT;
DROP TABLE IF EXISTS GROUPE;
DROP TABLE IF EXISTS HOTEL;
DROP TABLE IF EXISTS SALLE;




